listAreaCodes:
  handler: src/lambda/configs/listAreaCodes.handler
  events:
    - http:
        path: configs/areas
        method: get
        cors: true

listPartnerTypes:
  handler: src/lambda/configs/listPartnerTypes.handler
  events:
    - http:
        path: configs/partnerTypes
        method: get
        cors: true

listQuestionKeywords:
  handler: src/lambda/configs/listQuestionKeywords.handler
  events:
    - http:
        path: configs/questionKeywords
        method: get
        cors: true
