service:
  name: pawlog-aws
  app: pawlog-aws
  org: rnjssh96

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-apigw-binary

custom:
  serverless-offline:
    httpPort: 4000
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
    packagerOptions:
      scripts:
        - rm -rf node_modules/sharp
        - npm install --arch=x64 --platform=linux sharp
  apigwBinary:
    types:
      - image/*

provider:
  name: aws
  runtime: nodejs12.x
  stage: v1
  region: ap-southeast-1
  apiGateway:
    minimumCompressionSize: 1024
  vpc:
    securityGroupIds:
      - !ImportValue SecurityGroupName
    subnetIds:
      - !ImportValue PrivateSubnetAName
      - !ImportValue PrivateSubnetBName
      - !ImportValue PrivateSubnetCName
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - !ImportValue PartnerImageBucketArn
        - !Join
          - ''
          - - !ImportValue PartnerImageBucketArn
            - '/*'
        - !ImportValue QnAImageBucketArn
        - !Join
          - ''
          - - !ImportValue QnAImageBucketArn
            - '/*'
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    DB_HOST: !ImportValue PawlogRDSEndpoint
    # DB_HOST: 127.0.0.1
    DB_NAME: pawlog
    DB_USER: api
    DB_PSWD: aNDXJs3WGqUgXcJAXFcGG7xuB35eVV
    PARTNER_IMAGE_BUCKET: !ImportValue PartnerImageBucketName
    PARTNER_IMAGE_BUCKET_DOMAIN: !ImportValue PartnerImageBucketDomain
    QNA_IMAGE_BUCKET: !ImportValue QnAImageBucketName
    QNA_IMAGE_BUCKET_DOMAIN: !ImportValue QnAImageBucketDomain
functions:
  - ${file(./resource/function/authorizer.yml)}

  - ${file(./resource/function/trigger/cognito.yml)}

  - ${file(./resource/function/api/config.yml)}
  - ${file(./resource/function/api/user.yml)}
  - ${file(./resource/function/api/partner.yml)}
  - ${file(./resource/function/api/qna.yml)}
