service:
  name: pawlog-aws
  app: pawlog-aws
  org: rnjssh96

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
    packagerOptions:
      scripts:
        - rm -rf node_modules/sharp
        - npm install --arch=x64 --platform=linux sharp
  apigwBinary:
    types:
      - image/*
  serverless-offline:
    httpPort: 4000

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs12.x
  stage: v1
  region: ap-southeast-1
  apiGateway:
    minimumCompressionSize: 1024
  vpc:
    securityGroupIds:
      - Ref: PawlogSecurityGroup
    subnetIds:
      - Ref: PrivateSubnetA
      - Ref: PrivateSubnetB
      - Ref: PrivateSubnetC
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - !GetAtt S3BucketPartnerImage.Arn
        - !Join
          - ''
          - - !GetAtt S3BucketPartnerImage.Arn
            - '/*'
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    # DB_HOST: 127.0.0.1
    DB_HOST: !GetAtt PawlogRDS.Endpoint.Address
    DB_NAME: pawlog
    DB_USER: api
    DB_PSWD: aNDXJs3WGqUgXcJAXFcGG7xuB35eVV
    PARTNER_IMAGE_BUCKET: !Ref S3BucketPartnerImage
    PARTNER_IMAGE_BUCKET_DOMAIN: !GetAtt S3BucketPartnerImage.RegionalDomainName
    QNA_IMAGE_BUCKET: !Ref S3BucketQnAImage
    QNA_IMAGE_BUCKET_DOMAIN: !GetAtt S3BucketQnAImage.RegionalDomainName

functions:
  - customAuthorizer:
      handler: src/authorizer.handler
      environment:
        COGNITO_PROVIDER_URL: !GetAtt CognitoUserPoolPawlog.ProviderURL

  - ${file(./resource/trigger/cognito.yml)}

  - ${file(./resource/api/config.yml)}
  - ${file(./resource/api/user.yml)}
  - ${file(./resource/api/partner.yml)}
  - ${file(./resource/api/qna.yml)}

resources:
  - ${file(./resource/vpc/vpc.yml)}
  - ${file(./resource/vpc/security-group.yml)}
  - ${file(./resource/vpc/subnet.yml)}
  - ${file(./resource/vpc/route-table.yml)}

  - ${file(./resource/vpc/internet-gateway.yml)}
  - ${file(./resource/vpc/nat-gateway.yml)}

  - ${file(./resource/cognito/userpool.yml)}
  - ${file(./resource/cognito/identitypool.yml)}

  - ${file(./resource/rds.yml)}

  - ${file(./resource/s3/s3-bucket-partner-image.yml)}
  - ${file(./resource/s3/s3-bucket-qna-image.yml)}
