service:
  name: pawlog-aws
  app: pawlog-aws
  org: rnjssh96

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    httpPort: 4000

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    DB_HOST: 127.0.0.1
    DB_NAME: Pawlog
    DB_USER: root
    DB_PSWD: godqhrgkwk

resources:
  Resources:

functions:
  - ${file(./resource/function/config.yml)}
  - ${file(./resource/function/partner.yml)}
