service:
  name: pawlog-aws
  app: pawlog-aws
  org: rnjssh96

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    httpPort: 4000
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    USER_TABLE: ${self:resources.Resources.UserTable.Properties.TableName}
    PETSHOP_TABLE: ${self:resources.Resources.PetshopTable.Properties.TableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - 'Fn::GetAtt': [UserTable, Arn]
        - 'Fn::GetAtt': [PetshopTable, Arn]

resources:
  Resources:
    UserTable: ${file(./resource/dynamodb/user-table.yml)}
    PetshopTable: ${file(./resource/dynamodb/petshop-table.yml)}

functions:
  - ${file(./resource/function/petshop.yml)}
