service:
  name: pawlog-api
  app: pawlog-api
  org: Pawlog Company Limited

plugins:
  - serverless-apigw-binary
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
  apigwBinary:
    types:
      - image/*

provider:
  name: aws
  runtime: nodejs12.x
  stage: v1
  region: ap-southeast-1
  apiGateway:
    minimumCompressionSize: 1024
  vpc:
    securityGroupIds:
      - !ImportValue SecurityGroupName
    subnetIds:
      - !ImportValue PrivateSubnetAName
      - !ImportValue PrivateSubnetBName
      - !ImportValue PrivateSubnetCName
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - !ImportValue PartnerImageBucketArn
        - !Join
          - ''
          - - !ImportValue PartnerImageBucketArn
            - '/*'
        - !ImportValue QnAImageBucketArn
        - !Join
          - ''
          - - !ImportValue QnAImageBucketArn
            - '/*'
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    # DB_HOST: !ImportValue PawlogRDSEndpoint
    DB_HOST: 127.0.0.1
    DB_NAME: pawlog
    DB_USER: api
    DB_PSWD: aNDXJs3WGqUgXcJAXFcGG7xuB35eVV
    PARTNER_IMAGE_BUCKET: pawlog-partner-image
    PARTNER_IMAGE_BUCKET_DOMAIN: localhost:4572/s3/pawlog-partner-image
    QNA_IMAGE_BUCKET: pawlog-qna-image
    QNA_IMAGE_BUCKET_DOMAIN: localhost:4572/s3/pawlog-qna-image
    # PARTNER_IMAGE_BUCKET: !ImportValue PartnerImageBucketName
    # QNA_IMAGE_BUCKET: !ImportValue QnAImageBucketName
    # PARTNER_IMAGE_BUCKET_DOMAIN: !ImportValue PartnerImageBucketDomain
    # QNA_IMAGE_BUCKET_DOMAIN: !ImportValue QnAImageBucketDomain

functions:
  - ${file(./function/authorizer.yml)}

  - ${file(./function/trigger/cognito.yml)}

  - ${file(./function/api/config.yml)}
  - ${file(./function/api/user.yml)}
  - ${file(./function/api/partner.yml)}
  - ${file(./function/api/qna.yml)}
