service:
  name: pawlog-aws
  app: pawlog-aws
  org: rnjssh96

custom:
  pawlogPartnerImageBucket: pawlog-partner-image
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
    packagerOptions:
      scripts:
        - rm -rf node_modules/sharp
        - npm install --arch=x64 --platform=linux sharp
  serverless-offline:
    httpPort: 4000

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  apiGateway:
    minimumCompressionSize: 1024
  vpc:
    securityGroupIds:
      - Ref: PawlogSecurityGroup
    subnetIds:
      - Ref: PrivateSubnetA
      - Ref: PrivateSubnetB
      - Ref: PrivateSubnetC
  s3:
    pawlogPartnerImageBucket:
      name: ${self:custom.pawlogPartnerImageBucket}
      tags:
        - Key: Name
          Value: PawlogPartnerImageS3
      corsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - HEAD
              - GET
              - PUT
              - POST
              - DELETE
            MaxAge: 3000
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - arn:aws:s3:::${self:custom.pawlogPartnerImageBucket}/*
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    DB_HOST: 127.0.0.1
    # DB_HOST: !GetAtt PawlogRDS.Endpoint.Address
    DB_NAME: pawlog
    # DB_USER: admin
    DB_USER: root
    DB_PSWD: godqhrgkwk
    PARTNER_IMAGE_S3_DOMAIN: ${self:custom.pawlogPartnerImageBucket}.s3.ap-southeast-1.amazonaws.com

resources:
  - ${file(./resource/vpc/vpc.yml)}
  - ${file(./resource/vpc/security-group.yml)}
  - ${file(./resource/vpc/subnet.yml)}
  - ${file(./resource/vpc/route-table.yml)}

  - ${file(./resource/vpc/nat-gateway.yml)}
  - ${file(./resource/vpc/internet-gateway.yml)}

  - ${file(./resource/cognito/userpool.yml)}
  - ${file(./resource/cognito/identitypool.yml)}

  - ${file(./resource/rds.yml)}

functions:
  - ${file(./resource/function/config.yml)}
  - ${file(./resource/function/partner.yml)}
  - ${file(./resource/function/user.yml)}

  - ${file(./resource/trigger/s3.yml)}
