storage:
  Resources:
    PawlogRDS:
      Type: AWS::RDS::DBCluster
      Properties:
        Engine: aurora
        EngineMode: serverless
        EngineVersion: 5.6.10a
        DatabaseName: pawlog
        MasterUsername: admin
        MasterUserPassword: godqhrgkwk
        Port: 3306
        DBSubnetGroupName: !ImportValue PrivateSubnetGroupName
        VpcSecurityGroupIds:
          - !ImportValue SecurityGroupName
        ScalingConfiguration:
          AutoPause: false

    S3BucketPartnerImage:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: pawlog-partner-image
        Tags:
          - Key: Name
            Value: S3BucketPartnerImage

    S3BucketQnAImage:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: pawlog-qna-image
        Tags:
          - Key: Name
            Value: S3BucketQnAImage

  Outputs:
    PawlogRDSEndpoint:
      Value: !GetAtt PawlogRDS.Endpoint.Address
      Export:
        Name: PawlogRDSEndpoint

    PartnerImageBucketName:
      Value: !Ref S3BucketPartnerImage
      Export:
        Name: PartnerImageBucketName
    PartnerImageBucketArn:
      Value: !GetAtt S3BucketPartnerImage.Arn
      Export:
        Name: PartnerImageBucketArn
    PartnerImageBucketDomain:
      Value: !GetAtt S3BucketPartnerImage.RegionalDomainName
      Export:
        Name: PartnerImageBucketDomain

    QnAImageBucketName:
      Value: !Ref S3BucketQnAImage
      Export:
        Name: QnAImageBucketName
    QnAImageBucketArn:
      Value: !GetAtt S3BucketQnAImage.Arn
      Export:
        Name: QnAImageBucketArn
    QnAImageBucketDomain:
      Value: !GetAtt S3BucketQnAImage.RegionalDomainName
      Export:
        Name: QnAImageBucketDomain
