Resources:
  PawlogVPCInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: PawlogVPCInternetGateway

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    DependsOn: PawlogVPCInternetGateway
    Properties:
      InternetGatewayId: !Ref PawlogVPCInternetGateway
      VpcId: !Ref PawlogVPC

  IGRoute:
    Type: AWS::EC2::Route
    DependsOn: PawlogVPCInternetGateway
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: PawlogVPCInternetGateway
