Resources:
  PawlogPartnerImageS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: pawlog-partner-image
      Tags:
        - Key: Name
          Value: PawlogPartnerImageS3
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - HEAD
              - GET
              - PUT
              - POST
              - DELETE
            MaxAge: 3000
