Resources:
  PawlogRDS:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora
      EngineMode: serverless
      EngineVersion: 5.6.10a
      DatabaseName: pawlog
      MasterUsername: admin
      MasterUserPassword: godqhrgkwk
      Port: 3306
      DBSubnetGroupName:
        Ref: PrivateSubnetGroup
      VpcSecurityGroupIds:
        - Ref: PawlogSecurityGroup
      ScalingConfiguration:
        AutoPause: false
