listAreaCodes:
  handler: src/api/configs.listAreaCodes
  events:
    - http:
        path: configs/area
        method: get

listPartnerTypes:
  handler: src/api/configs.listPartnerTypes
  events:
    - http:
        path: configs/partnerType
        method: get
