Resources:
  S3BucketPartnerImage:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: pawlog-partner-image
      Tags:
        - Key: Name
          Value: S3BucketPartnerImage

Outputs:
  PartnerImageBucketName:
    Value: !Ref S3BucketPartnerImage
    Export:
      Name: PartnerImageBucketName
  PartnerImageBucketArn:
    Value: !GetAtt S3BucketPartnerImage.Arn
    Export:
      Name: PartnerImageBucketArn
  PartnerImageBucketDomain:
    Value: !GetAtt S3BucketPartnerImage.RegionalDomainName
    Export:
      Name: PartnerImageBucketDomain
