Resources:
  PublicSubnet:
    DependsOn: PawlogVPC
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: PawlogVPC
      AvailabilityZone: ${self:provider.region}a
      CidrBlock: 172.31.64.0/20
      Tags:
        - Key: Name
          Value: PublicSubnet

  PrivateSubnetA:
    DependsOn: PawlogVPC
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: PawlogVPC
      AvailabilityZone: ${self:provider.region}a
      CidrBlock: 172.31.16.0/20
      Tags:
        - Key: Name
          Value: PrivateSubnetA

  PrivateSubnetB:
    DependsOn: PawlogVPC
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: PawlogVPC
      AvailabilityZone: ${self:provider.region}b
      CidrBlock: 172.31.32.0/20
      Tags:
        - Key: Name
          Value: PrivateSubnetB

  PrivateSubnetC:
    DependsOn: PawlogVPC
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: PawlogVPC
      AvailabilityZone: ${self:provider.region}c
      CidrBlock: 172.31.48.0/20
      Tags:
        - Key: Name
          Value: PrivateSubnetC

  PrivateSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Private subnet group
      SubnetIds:
        - Ref: PrivateSubnetA
        - Ref: PrivateSubnetB
        - Ref: PrivateSubnetC
      Tags:
        - Key: Name
          Value: PrivateSubnetGroup
