Resources:
  PawlogUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: PawlogUserPool
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 2
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: family_name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: given_name
          AttributeDataType: String
          Mutable: true
          Required: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: True
          RequireNumbers: True
          RequireSymbols: False
          RequireUppercase: True
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK
        EmailSubjectByLink: 'Pawlog Email Confirmation'
        EmailMessageByLink: 'gogo: {##link##}'

  PawlogUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: pawloghk
      UserPoolId:
        Ref: PawlogUserPool

  PawlogUserPoolGoogleIDP:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      ProviderName: Google
      ProviderType: Google
      AttributeMapping:
        email: email
        name: name
        family_name: family_name
        given_name: given_name
        picture: picture
      ProviderDetails:
        client_id: 339366390860-o8lcvjns5middco4tegafmdeia60t6nc.apps.googleusercontent.com
        client_secret: lxku7tA9Ma-cZM1Iq7slFuxs
        authorize_scopes: email profile
      UserPoolId:
        Ref: PawlogUserPool

  PawlogUserPoolFacebookIDP:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      ProviderName: Facebook
      ProviderType: Facebook
      AttributeMapping:
        email: email
        name: name
        family_name: last_name
        given_name: first_name
        picture: picture
      ProviderDetails:
        client_id: '211743693267367'
        client_secret: 601671abba8d9b13646876cfebbed47e
        authorize_scopes: public_profile email
      UserPoolId:
        Ref: PawlogUserPool

  PawlogWebClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn:
      - PawlogUserPoolGoogleIDP
      - PawlogUserPoolFacebookIDP
    Properties:
      ClientName: PawlogWebClient
      UserPoolId:
        Ref: PawlogUserPool
      CallbackURLs:
        - http://localhost:3000/
      LogoutURLs:
        - http://localhost:3000/
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: False
      PreventUserExistenceErrors: ENABLED
      SupportedIdentityProviders:
        - COGNITO
        - Google
        - Facebook
